services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Knp\Component\Pager\Paginator: '@knp_paginator'

    # makes classes in src/UserBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppVerk\DatatableBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Repository,Tests,Doctrine}'
